const options = require("./config"); //options from config.js

const allPlugins = {
  typography: require("@tailwindcss/typography"),
  forms: require("@tailwindcss/forms"),
  containerQueries: require("@tailwindcss/container-queries"),
};

const plugins = Object.keys(allPlugins)
  .filter((k) => options.plugins[k])
  .map((k) => {
    if (k in options.plugins && options.plugins[k]) {
      return allPlugins[k];
    }
  });

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,php}"],
  darkMode: "class",
  separator: ':',
  theme: {
    screens: {
      'xs': '480px',
      'sm': '576px',
      'md': '768px',
      'lg': '992px',
      'xl': '1200px',
      'xxl': '1400px',
      'xxxl': '1600px'
    },
    colors: {
      transparent: 'transparent',
      black: '#000000',
      white:  '#ffffff',
      alert:  '#F3313A',
      warning:'#FFC300',
      success:'#00D764',
      red: '#FD2C55',
      tael: '#25F4EE',
      pink: '#FF66F1',
    },
    spacing: {
      '0': '0',
      '4': '0.25em',
      '6':  '0.375em',
      '8':  '0.5em',
      '10': '0.625em',
      '12': '0.75em',
      '14': '0.75em',
      '15': '0.938em',
      '16': '1em',
      '17': '1.063em',
      '18': '1.125em',
      '20': '1.25em',
      '22': '1.375em',
      '24': '1.5em',
      '30': '1.875em',
      '32': '2em',
      '40': '2.5em',
      '42': '2.625em',
      '44': '2.75em',
      '48': '3em',
      '56': '3.5em',
      '60': '3.75em',
      '64': '4em',
    },
    backgroundColor: theme => theme('colors'),
    backgroundPosition: {
      bottom:         'bottom',
      center:         'center',
      left:           'left',
      'left-bottom':  'left bottom',
      'left-top':     'left top',
      right:          'right',
      'right-bottom': 'right bottom',
      'right-top':    'right top',
      top:            'top',
    },
    backgroundSize: {
      auto:     'auto',
      cover:    'cover',
      contain:  'contain',
    },
    borderColor: theme => ({
      ...theme('colors'),
    }),
    borderRadius: {
      none:     '0',
      full:     '9999px',
      '4':      '0.25em',
      '8':      '0.5em',
    },
    borderWidth: {
      default: '1px',
      '0': '0',
      '2': '2px',
      '4': '4px',
      '8': '8px',
    },
    cursor: {
      auto: 'auto',
      default: 'default',
      pointer: 'pointer',
      'not-allowed': 'not-allowed',
    },
    fontFamily: {
      sopiaBold: [
        'sofia_pro_vhbold',
        'sans-serif'
      ],
      sopiaSemi: [
        'sofia_prosemi_bold',
        'sans-serif'
      ],
      sans: [
        'sofia_proregular',
        'sans-serif'
      ],
      heading: [
        'sofia_problack',
        'serif'
      ],
      icon: [
        'icon',
      ],
    },
    fontSize: {
      '12':   '0.75rem',
      '14':   '0.874rem',
      '18':   '1.125rem',
      '20':   '1.25rem',
      '22':   '1.375rem',
      '24':   '1.5rem',
      '25':   '1.563rem',
      '26':   '1.625rem',
      '30':   '1.875rem',
      '32':   '2rem',
      '40':   '2.5rem',
      '48':   '3rem',
      '56':   '3.5rem'
    },
    fontWeight: {
      '100':      '100',
      '200':      '200',
      '300':      '300',
      '400':      '400',
      '500':      '500',
      '600':      '600',
      '700':      '700',
      '800':      '800',
      '900':      '900',
    },
    lineHeight: {
      default:  '1',
      '11':    '1.1',
      '12':    '1.2',
      '13':    '1.3',
      '14':    '1.4',
      '15':    '1.5',
      '16':    '1.6',
      '2':     '2'

    },
    letterSpacing: {
      default:  '0',
      '04px':   '0.003rem',
      '025px':  '0.016rem',
      '050px':  '0.031rem',
      '1px':    '0.063rem'
    },
    height: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      full: '100%',
      screen: '100vh',
    }),
    inset: {
      '0': '0',
      auto: 'auto',
      '50': '50%',
      '100': '100%',
    },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
    },
    margin: (theme, { negative }) => ({
      auto: 'auto',
      ...theme('spacing'),
      ...negative(theme('spacing')),
    }),
    maxHeight: {
      full: '100%',
      screen: '100vh',
    },
    maxWidth: {
      xs: '20em',
      sm: '24em',
      md: '28em',
      lg: '32em',
      xl: '36em',
      '2xl': '42em',
      '3xl': '48em',
      '4xl': '56em',
      '5xl': '64em',
      '6xl': '72em',
      full: '100%',
    },
    minHeight: {
      '0': '0',
      full: '100%',
      screen: '100vh',
    },
    minWidth: {
      '0': '0',
      full: '100%',
    },
    objectPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    opacity: {
      '0': '0',
      '25': '0.25',
      '50': '0.5',
      '75': '0.75',
      '100': '1',
    },
    order: {
      first: '-9999',
      last: '9999',
      none: '0',
      '1': '1',
      '2': '2',
      '3': '3',
      '4': '4',
      '5': '5',
      '6': '6',
      '7': '7',
      '8': '8',
      '9': '9',
      '10': '10',
      '11': '11',
      '12': '12',
    },
    padding: theme => theme('spacing'),
    stroke: {
      current: 'currentColor',
    },
    textColor: theme => theme('colors'),
    width: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      '1/12': '8.333333%',
      '2/12': '16.666667%',
      '3/12': '25%',
      '4/12': '33.333333%',
      '5/12': '41.666667%',
      '6/12': '50%',
      '7/12': '58.333333%',
      '8/12': '66.666667%',
      '9/12': '75%',
      '10/12': '83.333333%',
      '11/12': '91.666667%',
      full: '100%',
      screen: '100vw',
    }),
    zIndex: {
      auto: 'auto',
      '0': '0',
      '10': '10',
      '20': '20',
      '30': '30',
      '40': '40',
      '50': '50',
    },
  },
  variants: {
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: ['responsive'],
    borderColor: ['responsive', 'hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    cursor: ['responsive'],
    display: ['responsive'],
    fill: ['responsive'],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: ['responsive'],
    fontFamily: ['responsive'],
    fontSize: ['responsive'],
    fontSmoothing: ['responsive'],
    fontStyle: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    inset: ['responsive'],
    justifyContent: ['responsive'],
    letterSpacing: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive'],
    order: ['responsive'],
    outline: ['responsive', 'focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    resize: ['responsive'],
    stroke: ['responsive'],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus'],
    textDecoration: ['responsive', 'hover', 'focus'],
    textTransform: ['responsive'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    width: ['responsive'],
    wordBreak: ['responsive'],
    zIndex: ['responsive'],
  },
  plugins: plugins,
};
